dist: trusty

sudo: required

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get -qq update
  - sudo apt-get install -y libhdf5-serial-dev   libboost-all-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest -VV

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email:
    recipients:
      - garethcmurphy@gmail.com
    on_success: always
    on_failure: always
